### ISSUE TITLE
Microsoft Dynamics CRM - Overview

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#842]
## Description
Update element overview docs to reflect high level description and remove error codes, transform data sections, and other generic information that is not specific to the element being reviewed

**Comment by rsbarbo** [comment]
@daniel-cherry Hi Dan - It would be interesting to add versions for all the elements that support different versions of a platform, for instance, We support 365 version of Microsoft Dynamics, but do not support 2011 version. Minimum version supported is 2013.

It would be awesome to add that to our documentation since we often get tickets asking for versions supported. Rapha Barbo
